/*************** PRODUCT ******************/
export const PRODUCT_LIST_HOME = "PRODUCT_LIST_HOME";
export const PRODUCT_LIST_DASHBOARD = "PRODUCT_LIST_DASHBOARD";
export const PRODUCT_LIST_LOADING = "PRODUCT_LIST_LOADING";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";

export const CHANGE_PRODUCT_INPUT = "CHANGE_PRODUCT_INPUT";
export const CHANGE_PRODUCT_INPUT_UPDATE = "CHANGE_PRODUCT_INPUT_UPDATE";
export const EMPTY_PRODUCT_MESSAGE = "EMPTY_PRODUCT_MESSAGE";
export const LOADING = "UPDATE_LOADING";
export const EDITING = "EDITING";
export const DELETING = "DELETING";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const EDIT_PRODUCT_INFO = "EDIT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
/*************** PRODUCT ******************/